name: "RTL_433 MQTT Bridge Custom"
version: "1.0.0"
slug: "rtl_433_mqtt"
description: "Un add-on pour envoyer les données rtl_433 vers MQTT"
url: "https://github.com/sebmorio/rtl_433_ha_addon"
startup: services
boot: auto
hassio_api: false
hassio_role: default
arch:
  - amd64
  - armv7
  - aarch64
map:
  - config:rw
options:
  mqtt_host: "homeassistant.local"
  mqtt_port: 1883
  mqtt_user: "homeassistant"
  mqtt_password: ""
schema:
  mqtt_host: str
  mqtt_port: int
  mqtt_user: str
  mqtt_password: str
