name: "RTL_433 MQTT Bridge Custom"
version: "0.0.1"
slug: "rtl_433_mqtt"
description: "Recuperation des donnees rtl_433 et integration dans MQTT"
url: "https://github.com/sebmorio/rtl_433_ha_addon"
startup: services
boot: auto
hassio_api: false
hassio_role: default
arch:
  - amd64
  - armv7
  - aarch64
map:
  - config:rw

# Acces aux peripheriques USB
devices:
  - "{device}:{device}:rwm"  # Acces aux peripheriques USB

privileged: true

# Options MQTT et USB configurables via l interface de Home Assistant
options:
  mqtt_host: "homeassistant.local"
  mqtt_port: 1883
  mqtt_user: ""
  mqtt_password: ""
  device: "/dev/bus/usb/002/003" i# Choix du port USB
schema:
  mqtt_host: str
  mqtt_port: int
  mqtt_user: str
  mqtt_password: password
  device: str

